name: Check hyperlinks

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install "mistune<3.1"  # a newer version is incompatible with nbconvert
        pip install pytest pytest-check-links

    - name: Check links
      run: |
        pytest --check-links README.md --check-links-ignore "http*"
        pytest --check-links tutorials --check-links-ignore "http*"
