name: Deploy MkDocs

on:
  push:
    branches: [main]

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-24.04
    steps:
      # Step 1: Checkout the repository
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # Step 2: Set up Python
      - uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.x"
          cache: "pip"

      # Step 3: Install MkDocs and dependencies
      - run: pip install mkdocs mkdocs-material mkdocs-pagetree-plugin
      # Step 4: Deploy to GitHub Pages
      - run: |
          mkdir -p gh-pages/docs
          cp -r tutorials/* gh-pages/docs
          cd gh-pages
          mv docs/mkdocs.yml mkdocs.yml
          echo "{{ pagetree }}" > docs/index.md
          mkdocs gh-deploy --force
